-- SESION 1
BEGIN;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
UPDATE accounts SET balance = 50 WHERE id = 1;



-- SESSION 2
BEGIN;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT balance FROM accounts WHERE id = 1;
-- Reads value from uncommitted transaction(SESSION 1)
COMMIT;


-- SESSION 1
ROLLBACK;