-- SESION 1
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT balance FROM accounts WHERE id = 1;




-- SESSION 2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
UPDATE accounts SET balance = 200 WHERE id = 1;

COMMIT;


-- SESSION 1
SELECT balance FROM accounts WHERE id = 1;
COMMIT;