-- SESION 1
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
SELECT * FROM accounts WHERE balance > 50;



-- SESSION 2
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
START TRANSACTION;
INSERT INTO accounts (id, name, balance) VALUES (2, 'New Account', 60);
COMMIT;


-- SESSION 1
SELECT * FROM accounts WHERE balance > 50;
COMMIT;